# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '40 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity for over 60 days, hence marked as "staled-issue". This issue will be closed in 7 days.'
        stale-pr-message: 'This PR has had no activity for over 60 days, hence marked as "staled-pr". This PR will be closed in 7 days.'
        stale-issue-label: 'staled-issue'
        stale-pr-label: 'staled-pr'
